/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -O3 -fno-strict-aliasing  -I/usr/share/nim -o /home/kavis/Documents/Project/ML_Project/Nim/nimcache/stats.o /home/kavis/Documents/Project/ML_Project/Nim/nimcache/stats.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg {
  RootObj Sup;
NI colonstate_;
NF m1;
NF l2;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef struct {
N_NIMCALL_PTR(NF, ClP_0) (NI x, void* ClE_0);
void* ClE_0;
} tyProc_Ih5g1dLHV2rxblmEB373cQ;
typedef N_CLOSURE_PTR(NF, TM_c39bwecZ2Jm9aw4nH5SppBdQ_5) (NI x);
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, main_tV0ryHF0fij4K2eoELmtsw)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, newSeq_vg7LhJDfsuQYl9cZfOCH1Fw)(NI len);
static N_INLINE(NI, len_dieebyw8huA9adTlIwdsH9bQstats)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qstats)(NI a, NI b);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, add_A9bDQDKw5SEqD3OvtOnC1bg)(NimStringDesc** result, NF x);
N_LIB_PRIVATE N_NIMCALL(NF, mean_7wwn1ZxbIjq3Cvy4dlT4fQ)(tySequence_qwqHTkRvwhrRyENtudHQ7g* vec);
N_LIB_PRIVATE N_NIMCALL(NI, sum_gbIPXmHbH9cB6gW9ceVVFvbQ)(NI* x, NI xLen_0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NF, variance_7wwn1ZxbIjq3Cvy4dlT4fQ_2)(tySequence_qwqHTkRvwhrRyENtudHQ7g* vec);
static N_NIMCALL(void, Marker_tyRef_RV6U9bTEvTd0j9byyYGt2Log)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NF, sum_o0A2tEZqgAaJbmC0q9asV1g)(NF* x, NI xLen_0);
static N_INLINE(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, map_BTJEbgdDz5pN29aNtvMDmOAstats)(NI* s, NI sLen_0, tyProc_Ih5g1dLHV2rxblmEB373cQ op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_CLOSURE(NF, colonanonymous__fJMx2HKLv5gudsrfn8L3fw)(NI x, void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(NF, roof__NI9cusyf8Wb9bNDqys9c3fp6g)(NF x, NI y);
N_LIB_PRIVATE N_NIMCALL(NF, std_7wwn1ZxbIjq3Cvy4dlT4fQ_3)(tySequence_qwqHTkRvwhrRyENtudHQ7g* vec);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_futureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strformatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strformatDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, statsDatInit000)(void);
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_Srvmve5MfW5nI06BIcThTg_;
extern TNimType NTI_xHTZrq9aYs6boc9bCba0JbpQ_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_RV6U9bTEvTd0j9byyYGt2Log_;
extern TNimType NTI_Zj5xKXgsXnI4n4hPS6nACA_;
STRING_LITERAL(TM_c39bwecZ2Jm9aw4nH5SppBdQ_2, "Mean: ", 6);
STRING_LITERAL(TM_c39bwecZ2Jm9aw4nH5SppBdQ_3, "Var: ", 5);
STRING_LITERAL(TM_c39bwecZ2Jm9aw4nH5SppBdQ_6, "Std: ", 5);

static N_INLINE(NI, len_dieebyw8huA9adTlIwdsH9bQstats)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NI result;
	result = (NI)0;
	result = ((((NI) 0) >= (NI)((NI)(x.b - x.a) + ((NI) 1))) ? ((NI) 0) : (NI)((NI)(x.b - x.a) + ((NI) 1)));
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qstats)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NF, mean_7wwn1ZxbIjq3Cvy4dlT4fQ)(tySequence_qwqHTkRvwhrRyENtudHQ7g* vec) {
	NF result;
	NI T1_;
	NI T2_;
	result = (NF)0;
	T1_ = (NI)0;
	T1_ = sum_gbIPXmHbH9cB6gW9ceVVFvbQ(vec->data, vec->Sup.len);
	T2_ = (vec ? vec->Sup.len : 0);
	result = ((NF)(((NF) (T1_))) / (NF)(((NF) (T2_))));
	return result;
}
static N_NIMCALL(void, Marker_tyRef_RV6U9bTEvTd0j9byyYGt2Log)(void* p, NI op) {
	tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg* a;
	a = (tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg*)p;
}

static N_INLINE(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, map_BTJEbgdDz5pN29aNtvMDmOAstats)(NI* s, NI sLen_0, tyProc_Ih5g1dLHV2rxblmEB373cQ op) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* result;
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*) newSeq((&NTI_Zj5xKXgsXnI4n4hPS6nACA_), ((NI) (sLen_0)));
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = sLen_0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				result->data[i] = op.ClE_0? op.ClP_0(s[i], op.ClE_0):((TM_c39bwecZ2Jm9aw4nH5SppBdQ_5)(op.ClP_0))(s[i]);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

N_LIB_PRIVATE N_CLOSURE(NF, colonanonymous__fJMx2HKLv5gudsrfn8L3fw)(NI x, void* ClE_0) {
	NF result;
	tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg* colonenvP_;
	NF T1_;
	result = (NF)0;
	colonenvP_ = (tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg*) ClE_0;
	T1_ = (NF)0;
	T1_ = roof__NI9cusyf8Wb9bNDqys9c3fp6g(((NF)(((NF) (x))) - (NF)((*colonenvP_).m1)), ((NI) 2));
	result = ((NF)(T1_) / (NF)(((NF)((*colonenvP_).l2) - (NF)(1.0000000000000000e+00))));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, variance_7wwn1ZxbIjq3Cvy4dlT4fQ_2)(tySequence_qwqHTkRvwhrRyENtudHQ7g* vec) {
	NF result;
	tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg* colonenv_;
	NI T1_;
	tyProc_Ih5g1dLHV2rxblmEB373cQ T2_;
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* T3_;
	result = (NF)0;
	colonenv_ = (tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg*)0;
	colonenv_ = (tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg*) newObj((&NTI_RV6U9bTEvTd0j9byyYGt2Log_), sizeof(tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg));
	(*colonenv_).Sup.m_type = (&NTI_Srvmve5MfW5nI06BIcThTg_);
	T1_ = (vec ? vec->Sup.len : 0);
	(*colonenv_).l2 = ((NF) (T1_));
	(*colonenv_).m1 = mean_7wwn1ZxbIjq3Cvy4dlT4fQ(vec);
	memset((void*)(&T2_), 0, sizeof(T2_));
	T2_.ClP_0 = colonanonymous__fJMx2HKLv5gudsrfn8L3fw; T2_.ClE_0 = colonenv_;
	T3_ = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
	T3_ = map_BTJEbgdDz5pN29aNtvMDmOAstats(vec->data, vec->Sup.len, T2_);
	result = sum_o0A2tEZqgAaJbmC0q9asV1g(T3_->data, T3_->Sup.len);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, std_7wwn1ZxbIjq3Cvy4dlT4fQ_3)(tySequence_qwqHTkRvwhrRyENtudHQ7g* vec) {
	NF result;
	NF T1_;
	result = (NF)0;
	T1_ = (NF)0;
	T1_ = variance_7wwn1ZxbIjq3Cvy4dlT4fQ_2(vec);
	result = sqrt(T1_);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, main_tV0ryHF0fij4K2eoELmtsw)(void) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* a;
	NI i;
	tySequence_qwqHTkRvwhrRyENtudHQ7g* result;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T1_;
	NI T2_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T6_;
	NimStringDesc* fmtRes;
	NF T7_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T8_;
	NimStringDesc* fmtRes_2;
	NF T9_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T10_;
	NimStringDesc* fmtRes_3;
	NF T11_;
	i = ((NI) 0);
	T1_ = dotdot__vDQySKWzgnxQdUarow6k5Qstats(((NI) 1), ((NI) 10000000));
	T2_ = (NI)0;
	T2_ = len_dieebyw8huA9adTlIwdsH9bQstats(T1_);
	result = newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI) (T2_)));
	{
		NI x;
		NI res;
		x = (NI)0;
		res = ((NI) 1);
		{
			while (1) {
				if (!(res <= ((NI) 10000000))) goto LA5;
				x = res;
				result->data[i] = x;
				i += ((NI) 1);
				res += ((NI) 1);
			} LA5: ;
		}
	}
	a = result;
	memset((void*)T6_, 0, sizeof(T6_));
	fmtRes = rawNewString(((NI) 24));
	fmtRes = resizeString(fmtRes, 6);
appendString(fmtRes, ((NimStringDesc*) &TM_c39bwecZ2Jm9aw4nH5SppBdQ_2));
	T7_ = (NF)0;
	T7_ = mean_7wwn1ZxbIjq3Cvy4dlT4fQ(a);
	add_A9bDQDKw5SEqD3OvtOnC1bg((&fmtRes), T7_);
	T6_[0] = copyString(fmtRes);
	echoBinSafe(T6_, 1);
	memset((void*)T8_, 0, sizeof(T8_));
	fmtRes_2 = rawNewString(((NI) 27));
	fmtRes_2 = resizeString(fmtRes_2, 5);
appendString(fmtRes_2, ((NimStringDesc*) &TM_c39bwecZ2Jm9aw4nH5SppBdQ_3));
	T9_ = (NF)0;
	T9_ = variance_7wwn1ZxbIjq3Cvy4dlT4fQ_2(a);
	add_A9bDQDKw5SEqD3OvtOnC1bg((&fmtRes_2), T9_);
	T8_[0] = copyString(fmtRes_2);
	echoBinSafe(T8_, 1);
	memset((void*)T10_, 0, sizeof(T10_));
	fmtRes_3 = rawNewString(((NI) 22));
	fmtRes_3 = resizeString(fmtRes_3, 5);
appendString(fmtRes_3, ((NimStringDesc*) &TM_c39bwecZ2Jm9aw4nH5SppBdQ_6));
	T11_ = (NF)0;
	T11_ = std_7wwn1ZxbIjq3Cvy4dlT4fQ_3(a);
	add_A9bDQDKw5SEqD3OvtOnC1bg((&fmtRes_3), T11_);
	T10_[0] = copyString(fmtRes_3);
	echoBinSafe(T10_, 1);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_futureDatInit000();
	stdlib_mathDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_strformatDatInit000();
	statsDatInit000();
	stdlib_macrosInit000();
	stdlib_sequtilsInit000();
	stdlib_futureInit000();
	stdlib_mathInit000();
	stdlib_parseutilsInit000();
	stdlib_unicodeInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_strformatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	{
		if (!NIM_TRUE) goto LA3_;
		main_tV0ryHF0fij4K2eoELmtsw();
	}
	LA3_: ;
}

NIM_EXTERNC N_NOINLINE(void, statsDatInit000)(void) {
static TNimNode* TM_c39bwecZ2Jm9aw4nH5SppBdQ_4[3];
static TNimNode TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[4];
NTI_Srvmve5MfW5nI06BIcThTg_.size = sizeof(tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg);
NTI_Srvmve5MfW5nI06BIcThTg_.kind = 17;
NTI_Srvmve5MfW5nI06BIcThTg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
NTI_Srvmve5MfW5nI06BIcThTg_.flags = 1;
TM_c39bwecZ2Jm9aw4nH5SppBdQ_4[0] = &TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[1];
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[1].kind = 1;
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[1].offset = offsetof(tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg, colonstate_);
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[1].typ = (&NTI_xHTZrq9aYs6boc9bCba0JbpQ_);
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[1].name = ":state";
TM_c39bwecZ2Jm9aw4nH5SppBdQ_4[1] = &TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[2];
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[2].kind = 1;
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[2].offset = offsetof(tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg, m1);
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[2].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[2].name = "m1";
TM_c39bwecZ2Jm9aw4nH5SppBdQ_4[2] = &TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[3];
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[3].kind = 1;
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[3].offset = offsetof(tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg, l2);
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[3].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[3].name = "l2";
TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[0].len = 3; TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[0].kind = 2; TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[0].sons = &TM_c39bwecZ2Jm9aw4nH5SppBdQ_4[0];
NTI_Srvmve5MfW5nI06BIcThTg_.node = &TM_c39bwecZ2Jm9aw4nH5SppBdQ_0[0];
NTI_RV6U9bTEvTd0j9byyYGt2Log_.size = sizeof(tyObject_Env_statsdotnim__Srvmve5MfW5nI06BIcThTg*);
NTI_RV6U9bTEvTd0j9byyYGt2Log_.kind = 22;
NTI_RV6U9bTEvTd0j9byyYGt2Log_.base = (&NTI_Srvmve5MfW5nI06BIcThTg_);
NTI_RV6U9bTEvTd0j9byyYGt2Log_.marker = Marker_tyRef_RV6U9bTEvTd0j9byyYGt2Log;
}

