/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -O3 -fno-strict-aliasing  -I/usr/share/nim -o /home/kavis/Documents/Project/ML_Project/Nim/nimcache/stdlib_math.o /home/kavis/Documents/Project/ML_Project/Nim/nimcache/stdlib_math.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_q4xn9bvzjB0QCTcS8bELuDQ tyTuple_q4xn9bvzjB0QCTcS8bELuDQ;
struct tyTuple_q4xn9bvzjB0QCTcS8bELuDQ {
NF Field0;
NI Field1;
};
static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAwmath)(NF* x, NF y);

N_LIB_PRIVATE N_NIMCALL(NI, sum_gbIPXmHbH9cB6gW9ceVVFvbQ)(NI* x, NI xLen_0) {
	NI result;
	result = (NI)0;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < xLen_0)) goto LA3;
				i = x[i_2];
				result = (NI)(result + i);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, sum_o0A2tEZqgAaJbmC0q9asV1g)(NF* x, NI xLen_0) {
	NF result;
	result = (NF)0;
	{
		NF i;
		NI i_2;
		i = (NF)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < xLen_0)) goto LA3;
				i = x[i_2];
				result = ((NF)(result) + (NF)(i));
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

static N_INLINE(void, stareq__7kHiltrvRlcg6wSYR3CxAwmath)(NF* x, NF y) {
	(*x) = ((NF)((*x)) * (NF)(y));
}

N_LIB_PRIVATE N_NIMCALL(NF, roof__NI9cusyf8Wb9bNDqys9c3fp6g)(NF x, NI y) {
	NF result;
	tyTuple_q4xn9bvzjB0QCTcS8bELuDQ T1_;
	NF x_2;
	NI y_2;
	result = (NF)0;
	T1_.Field0 = x;
	T1_.Field1 = y;
	x_2 = T1_.Field0;
	y_2 = T1_.Field1;
	result = 1.0000000000000000e+00;
	{
		while (1) {
			{
				if (!!(((NI)(((NI) (y_2)) & ((NI) 1)) == ((NI) 0)))) goto LA6_;
				stareq__7kHiltrvRlcg6wSYR3CxAwmath((&result), x_2);
			}
			LA6_: ;
			y_2 = ((NI) ((NI)((NU64)(((NI) (y_2))) >> (NU64)(((NI) 1)))));
			{
				if (!(((NI) (y_2)) == ((NI) 0))) goto LA10_;
				goto LA2;
			}
			LA10_: ;
			stareq__7kHiltrvRlcg6wSYR3CxAwmath((&x_2), x_2);
		}
	} LA2: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void) {
}

