/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -O3 -fno-strict-aliasing  -I/usr/share/nim -o /home/kavis/Documents/Project/ML_Project/Nim/nimcache/stdlib_sequtils.o /home/kavis/Documents/Project/ML_Project/Nim/nimcache/stdlib_sequtils.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op);
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_Zj5xKXgsXnI4n4hPS6nACA_;
static N_NIMCALL(void, Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* a;
	NI T1_;
	a = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)p;
	T1_ = (NI)0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void) {
NTI_Zj5xKXgsXnI4n4hPS6nACA_.size = sizeof(tySequence_Zj5xKXgsXnI4n4hPS6nACA*);
NTI_Zj5xKXgsXnI4n4hPS6nACA_.kind = 24;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.base = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTI_Zj5xKXgsXnI4n4hPS6nACA_.flags = 2;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.marker = Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA;
}

